# Generated by Django 4.2.2 on 2023-06-07 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
    ]
